safe: true
lsi: false
pygments: true
markdown: kramdown
url: http://plugins.jpry.com
permalink: /blog/:title.html
paginate: 10
paginate_path: /blog/page:num
exclude:
  - README.md

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap

timezone: America/New_York
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Jeremy Pry"
