baseurl: ""
url: "http://plugins.jpry.com"
title: "Pry's Plugins"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-sitemap

timezone: America/New_York
defaults:
  -
    scope:
      path: ""
    values:
      author: "Jeremy Pry"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
